version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
  - develop
clone_depth: 1
before_build:
    - cmd: nuget restore
build:
  verbosity: normal
notifications:
- provider: Email
  to:
  - jitedev+appveyor@gmail.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true